CREATE DATABASE TELANGANA;
SELECT * FROM domestic_visitors;
SELECT * FROM FOREIGN_VISITORS;
SELECT * FROM DISTRICT_POPULATION;
SELECT R.DISTRICT, (R.DOMESTICV+R.FOREIGNV) AS TOTAL_VISITORS FROM 
	(SELECT D.DISTRICT,SUM(D.VISITORS) AS DOMESTICV,SUM(F.VISITORS) 
	AS FOREIGNV FROM
	DOMESTIC_VISITORS D
	INNER JOIN 
	foreign_visitors F 
	ON 
	D.DISTRICT=F.DISTRICT 
	GROUP BY D.DISTRICT)R
WHERE (R.DOMESTICV+R.FOREIGNV) =0;


-----i. total visitors per year
WITH DOMESTIC AS (
	SELECT YEAR ,SUM(VISITORS) AS DOMESTIC_VISIT FROM DOMESTIC_VISITORS GROUP BY YEAR
		),
	FOREIGN1 AS (
	SELECT YEAR , SUM(VISITORS) AS FOREIGN_VISIT  FROM FOREIGN_VISITORS GROUP BY YEAR
	),
	TOTAL_year AS (
	SELECT D.YEAR,D.DOMESTIC_VISIT,F.FOREIGN_VISIT ,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL
	FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	D.YEAR=F.YEAR
	)
SELECT * FROM TOTAL_year ORDER BY year;

----- 1. LIST THE TOP 10 DISTRICTS THAT HAVE THE HIGHEST NUMBER OF DOMESTIC VISITORS OVERALL(2016-2019)

SELECT TOP 10 DISTRICT, 
SUM(VISITORS) "TOTAL_VISITORS" 
FROM domestic_visitors
GROUP  BY DISTRICT 
ORDER BY TOTAL_VISITORS DESC;

 -----2i. List down the top 3 districts based on compounded annual growth rate (CAGR) of visitors between (2016 - 2019)
WITH DOMESTIC AS (
	SELECT DISTRICT, SUM(VISITORS) AS DOMESTIC_VISIT,YEAR  FROM DOMESTIC_VISITORS GROUP BY DISTRICT,YEAR
		),
	FOREIGN1 AS (
	SELECT DISTRICT, SUM(VISITORS) AS FOREIGN_VISIT,YEAR  FROM FOREIGN_VISITORS GROUP BY DISTRICT,YEAR
	),
	TOTAL_VI AS (
	SELECT D.DISTRICT,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL_VISITORS, 
	D.YEAR FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.YEAR=F.YEAR
	AND D.DISTRICT=F.DISTRICT)
	),
		FIRST_YEAR AS (
			SELECT DISTRICT, YEAR AS FIRST_YEAR, TOTAL_VISITORS 
			FROM TOTAL_VI 
			WHERE YEAR = 2016
		),
		LAST_YEAR AS ( 
			SELECT DISTRICT, YEAR AS LAST_YEAR, TOTAL_VISITORS 
			FROM TOTAL_VI 
			WHERE YEAR = 2019
			),
				CAGR_DATA AS (
					SELECT A.DISTRICT, F.TOTAL_VISITORS AS "FIRST_YEAR",
					A.TOTAL_VISITORS AS LAST_YEAR,
					CASE WHEN F.TOTAL_VISITORS=0 
						THEN 0
					ELSE 
						ROUND(((POWER(CAST((A.TOTAL_VISITORS/F.TOTAL_VISITORS) AS FLOAT),
						(1.0/3.0))-1)*100),2) 
					END 
					AS "CAGR(2016-2019)"
					FROM LAST_YEAR A
					INNER JOIN 
					FIRST_YEAR F
					ON A.DISTRICT=F.DISTRICT
				)
SELECT TOP 3 * FROM CAGR_DATA ORDER BY 'CAGR(2016-2019)' DESC;


------3.  List down the bottom 3 districts based on compounded annual growth rate (CAGR) of visitors between (2016 - 2019)
WITH DOMESTIC AS (
	SELECT DISTRICT, SUM(VISITORS) AS DOMESTIC_VISIT,YEAR  FROM DOMESTIC_VISITORS GROUP BY DISTRICT,YEAR
		),
	FOREIGN1 AS (
	SELECT DISTRICT, SUM(VISITORS) AS FOREIGN_VISIT,YEAR  FROM FOREIGN_VISITORS GROUP BY DISTRICT,YEAR
	),
	TOTAL_VI AS (
	SELECT D.DISTRICT,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL_VISITORS, 
	D.YEAR FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.YEAR=F.YEAR
	AND D.DISTRICT=F.DISTRICT)
	),
		FIRST_YEAR AS (
			SELECT DISTRICT, YEAR AS FIRST_YEAR, TOTAL_VISITORS 
			FROM TOTAL_VI 
			WHERE YEAR = 2016
		),
		LAST_YEAR AS ( 
			SELECT DISTRICT, YEAR AS LAST_YEAR, TOTAL_VISITORS 
			FROM TOTAL_VI 
			WHERE YEAR = 2019
			),
				CAGR_DATA AS (
					SELECT A.DISTRICT, F.TOTAL_VISITORS AS "FIRST_YEAR",
					A.TOTAL_VISITORS AS LAST_YEAR,
					CASE WHEN F.TOTAL_VISITORS=0 
						THEN 0
					ELSE 
						ROUND(((POWER(CAST((A.TOTAL_VISITORS/F.TOTAL_VISITORS) AS FLOAT),
						(1.0/3.0))-1)*100),2) 
					END 
					AS "CAGR(2016-2019)"
					FROM LAST_YEAR A
					INNER JOIN 
					FIRST_YEAR F
					ON A.DISTRICT=F.DISTRICT
				)
SELECT TOP 3 * FROM CAGR_DATA  
ORDER BY 'CAGR(2016-2019)';




-------4. What are the peak and low season months for Hyderabad based on the data from 2016 to 2019 for Hyderabad district
WITH DOMESTIC AS (
	SELECT DISTRICT, SUM(VISITORS) AS DOMESTIC_VISIT,MONTH  FROM DOMESTIC_VISITORS GROUP BY DISTRICT,MONTH
		),
	FOREIGN1 AS (
	SELECT DISTRICT, SUM(VISITORS) AS FOREIGN_VISIT,MONTH  FROM FOREIGN_VISITORS GROUP BY DISTRICT,MONTH
	),
	TOTAL_VI AS (
	SELECT D.DISTRICT,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL, 
	D.MONTH FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.MONTH=F.MONTH
	AND D.DISTRICT=F.DISTRICT)
	),
		HYDERABAD AS (
			SELECT DISTRICT,MONTH, 
			TOTAL AS TOTAL 
			FROM TOTAL_VI 
			WHERE DISTRICT= 'Hyderabad'
		)
SELECT * FROM HYDERABAD  ORDER BY TOTAL DESC;


------- 5.  Show the top & bottom 3 districts with high domestic to foreign tourist ratio

SELECT TOP 3 * FROM
	(SELECT  R.DISTRICT, 
	CASE WHEN R.FOREIGNT =0 
		THEN 0
	ELSE 
		ROUND((R.DOMESTIC/R.FOREIGNT),2)
	END AS "RATIO" 
	FROM
		(SELECT D.DISTRICT,CAST(SUM(D.VISITORS) AS FLOAT) AS 
		"DOMESTIC", CAST(SUM(F.VISITORS) AS FLOAT) AS
		"FOREIGNT" FROM domestic_visitors D
		INNER JOIN foreign_visitors F
		ON D.district=F.district 
		GROUP BY D.district)R)RA
WHERE RA.RATIO !=0
ORDER BY RA.RATIO;


 ------6. List down the  annual growth rate (AGR) of visitors between (2016 - 2019) IN DISTRICTS WITH HIGH & LOW CAGR
WITH DOMESTIC AS (
	SELECT DISTRICT, SUM(VISITORS) AS DOMESTIC_VISIT,YEAR  FROM DOMESTIC_VISITORS GROUP BY DISTRICT,YEAR
	),
	FOREIGN1 AS (
	SELECT DISTRICT, SUM(VISITORS) AS FOREIGN_VISIT,YEAR  FROM FOREIGN_VISITORS GROUP BY DISTRICT,YEAR
	),
	TOTAL AS (
	SELECT D.DISTRICT,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL_VISITORS, 
	D.YEAR AS YEARS FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.YEAR=F.YEAR
	AND D.DISTRICT=F.DISTRICT)
	),
		GROWTH AS (
			SELECT W.DISTRICT,W.YEARS AS "PREVIOUS_YEARS",W.TOTAL_VISITORS 			
			AS "PREVIOUS_VISITORS",D.YEARS AS "CURRENT_YEAR",
			D.TOTAL_VISITORS AS "CURRENT_VISITORS",
			CASE WHEN
				W.TOTAL_VISITORS=0 
					THEN 0
			ELSE 
				ROUND(((CAST((D.TOTAL_VISITORS-W.TOTAL_VISITORS) AS FLOAT)
				/W.TOTAL_VISITORS)*100),2) END AS "PCT_CHANGE"
			FROM TOTAL W
			INNER JOIN
			TOTAL D
			ON 
				(W.YEARS+1=D.YEARS
				AND W.DISTRICT=D.DISTRICT
				)
			)

SELECT DISTRICT, CURRENT_YEAR AS "YEAR",CURRENT_VISITORS AS
 "TOTAL_VISITORS" ,PCT_CHANGE FROM GROWTH
 WHERE (DISTRICT = 'Mancherial') OR  
(DISTRICT = 'Jayashankar Bhoopalpally') OR 
(DISTRICT = 'Warangal (Rural)') ORDER BY DISTRICT;

-------PART 2-----
--------6. List the top & bottom 5 districts based on 'population to tourist footfall ratio*' ratio in 2019

WITH DOMESTIC AS (
	SELECT DISTRICT, SUM(VISITORS) AS DOMESTIC_VISIT,YEAR  FROM DOMESTIC_VISITORS GROUP BY DISTRICT,YEAR
	),
	FOREIGN1 AS (
	SELECT DISTRICT, SUM(VISITORS) AS FOREIGN_VISIT,YEAR  FROM FOREIGN_VISITORS GROUP BY DISTRICT,YEAR
	),
	VISITORS AS (
	SELECT D.DISTRICT,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL_VISITORS, 
	D.YEAR FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.YEAR=F.YEAR
	AND D.DISTRICT=F.DISTRICT)
	WHERE D.YEAR='2019'
	),
		POPULATION AS (
			SELECT V.DISTRICT,V.TOTAL_VISITORS,P.POPULATION 
			FROM VISITORS V
			LEFT JOIN 
			DISTRICT_POPULATION P
			ON V.DISTRICT=P.DISTRICT
			WHERE TOTAL_VISITORS != 0
			),
			FOOTBALL_RATIO AS (
				SELECT DISTRICT,TOTAL_VISITORS, POPULATION,
				ROUND((TOTAL_VISITORS/POPULATION),2) AS "FOOTBALL RATIO"
				FROM POPULATION
				)
SELECT TOP 5 * FROM FOOTBALL_RATIO  ORDER BY "FOOTBALL RATIO" DESC ;


-------7.What will be the projected number of domestic and foreign tourists in Hyderabad in 2025 based on the growth rate from previous years

WITH DOMESTIC AS (
	SELECT DISTRICT,YEAR , SUM(VISITORS) AS DOMESTIC_VISIT FROM DOMESTIC_VISITORS GROUP BY DISTRICT,YEAR
	),
	FOREIGN1 AS (
	SELECT DISTRICT,YEAR , SUM(VISITORS) AS FOREIGN_VISIT FROM FOREIGN_VISITORS GROUP BY DISTRICT,YEAR
	),
	HYDERABAD AS (
	SELECT D.DISTRICT,D.YEAR,D.DOMESTIC_VISIT, F.FOREIGN_VISIT
	FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.YEAR=F.YEAR
	AND D.DISTRICT=F.DISTRICT)
	WHERE D.DISTRICT = 'HYDERABAD'
	)
SELECT * FROM HYDERABAD;

--------8. Estimate the projected revenue for Hyderabad in 2025 based on average spend per tourist 
WITH DOMESTIC AS (
	SELECT DISTRICT,YEAR, SUM(VISITORS) AS DOMESTIC_VISIT FROM DOMESTIC_VISITORS GROUP BY DISTRICT,YEAR 
	HAVING DISTRICT= 'HYDERABAD'
		),
	FOREIGN1 AS (
	SELECT DISTRICT ,YEAR ,SUM(VISITORS) AS FOREIGN_VISIT FROM FOREIGN_VISITORS GROUP BY DISTRICT,YEAR
	HAVING DISTRICT= 'HYDERABAD'
	),
	TOTAL_VI AS (
	SELECT D.DISTRICT,D.YEAR,(D.DOMESTIC_VISIT*1200) AS "DOMESTIC_REVENUE",
	(F.FOREIGN_VISIT*5600) AS "FOREIGN_REVENUE"
	 FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON (D.YEAR=F.YEAR)
	)
SELECT *, (DOMESTIC_REVENUE+FOREIGN_REVENUE) AS "TOTAL_REVENUE" FROM TOTAL_VI;


------10. MONTH WITH HIGHEST TOURISM
WITH DOMESTIC AS (
	SELECT SUM(VISITORS) AS DOMESTIC_VISIT,MONTH  FROM DOMESTIC_VISITORS GROUP BY MONTH
	),
	FOREIGN1 AS (
	SELECT  SUM(VISITORS) AS FOREIGN_VISIT,MONTH  FROM FOREIGN_VISITORS GROUP BY MONTH
	),
	TOTAL_VI AS (
	SELECT D.MONTH,D.DOMESTIC_VISIT,F.FOREIGN_VISIT,(D.DOMESTIC_VISIT+ F.FOREIGN_VISIT) AS TOTAL
	FROM DOMESTIC D INNER JOIN FOREIGN1 F
	ON
	(D.MONTH=F.MONTH) 
	)
SELECT MONTH,SUM(DOMESTIC_VISIT) AS DOMESTIC_VISIT,SUM(FOREIGN_VISIT) AS FOREIGN_VISIT,
 SUM(TOTAL) AS "TOTAL_VISITORS" FROM TOTAL_VI GROUP BY MONTH;

 
 
 